export const SELECT_PRODUCT = "SELECT_PRODUCT";
export const REQUEST_PURCHASE_PRODUCT = "REQUEST_PURCHASE_PRODUCT";
export const HANDLE_PURCHASE_SUCCESS = "HANDLE_PURCHASE_SUCCESS";
export const HANDLE_PURCHASE_FAILURE = "HANDLE_PURCHASE_FAILURE";